### PR TITLE
Up and running

### PR DESCRIPTION
**Pull request by Mu-Gee**
Got everything up and running well, squashed a few bugs here and there as seen in the commits. Check it out.

### CODE REVIEW

**Comment by Ndegwadavid** [comment]
Lemme look in to it too..
Does the index page reflect or i should create the index page?

**Comment by Ndegwadavid** [comment]
i also think of changing the name :) JPD was a hypothetical project name

**Comment by Mu-Gee** [comment]
There's no index page, didn't come across it

**Comment by Mu-Gee** [comment]
Make it count.

**Pull request merged**
